blank_issues_enabled: true
contact_links:
  - name: Qiskit API feedback
    url: https://github.com/Qiskit/qiskit/issues/new/choose
    about: Open an issue in the Qiskit repository for the docs found at https://docs.quantum.ibm.com/api/qiskit.
  - name: Qiskit Runtime Client API feedback
    url: https://github.com/Qiskit/qiskit-ibm-runtime/issues/new/choose
    about: Open an issue in the qiskit-ibm-runtime repository for the docs found at https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/runtime_service.
