# For notebooks to be tested "normally" (no mocking)
notebooks_normal_test = [
    "docs/guides/construct-circuits.ipynb",
    "docs/guides/circuit-library.ipynb",
    "docs/guides/visualize-circuits.ipynb",
    "docs/guides/classical-feedforward-and-control-flow.ipynb",
    "docs/guides/operators-overview.ipynb",
    "docs/guides/pulse.ipynb",
    "docs/guides/save-circuits.ipynb",
    "docs/guides/dynamic-circuits-considerations.ipynb",
    "docs/guides/get-qpu-information.ipynb",
    "docs/guides/save-jobs.ipynb",
    "docs/guides/visualize-results.ipynb",
    "docs/guides/common-parameters.ipynb",
    "docs/guides/create-transpiler-plugin.ipynb",
    "docs/guides/custom-backend.ipynb",
    "docs/guides/custom-transpiler-pass.ipynb",
    "docs/guides/defaults-and-configuration-options.ipynb",
    "docs/guides/dynamical-decoupling-pass-manager.ipynb",
    "docs/guides/represent-quantum-computers.ipynb",
    "docs/guides/set-optimization.ipynb",
    "docs/guides/transpile-with-pass-managers.ipynb",
    "docs/guides/transpiler-plugins.ipynb",
    "docs/guides/transpiler-stages.ipynb",
    "docs/guides/build-noise-models.ipynb",
    "docs/guides/local-testing-mode.ipynb",
    "docs/guides/plot-quantum-states.ipynb",
    "docs/guides/simulate-with-qiskit-aer.ipynb",
    "docs/guides/simulate-stabilizer-circuits.ipynb",
    "docs/guides/operator-class.ipynb",
    "docs/guides/error-mitigation-and-suppression-techniques.ipynb",
    "docs/guides/fractional-gates.ipynb",
    "tutorials/explore-composer/explore-composer.ipynb",
]

# Don't test the following notebooks (this section can include glob patterns)
notebooks_exclude = [
    "scripts/ibm-quantum-learning-uploader/test/template.ipynb",
    "scripts/tutorial-uploader/lib/test-data/simple-tutorial/notebook.ipynb",
    "**/.ipynb_checkpoints/**",
    # The following notebooks are broken and need fixing
    "tutorials/submitting-transpiled-circuits/submitting-transpiled-circuits.ipynb",
]

# The following notebooks submit jobs that can be mocked with a simulator
notebooks_that_submit_jobs = [
    "tutorials/chsh-inequality/chsh-inequality.ipynb",
    "tutorials/grovers-algorithm/grovers.ipynb",
    "tutorials/quantum-approximate-optimization-algorithm/qaoa.ipynb",
    "tutorials/variational-quantum-eigensolver/vqe.ipynb",
]

# The following notebooks submit jobs that are too big to mock with a simulator (or use functions that aren't supported on sims)
# A job is "too big" if a cell can't run in under 5 mins, or we run out of
# memory on a reasonable device.
notebooks_no_mock = [
    "docs/guides/hello-world.ipynb",
    "tutorials/combine-error-mitigation-options-with-the-estimator-primitive/combine-error-mitigation-options-with-the-estimator-primitive.ipynb",
    "tutorials/repeat-until-success/repeat-until-success.ipynb",
    "tutorials/build-repetition-codes/build-repetition-codes.ipynb",
    "tutorials/qaoa-utility-scale/qopt_example.ipynb",
]
