# Used to find all notebooks in the repo
all_notebooks = "[!.]*/**/*.ipynb"

# Always exclude notebooks matching the following patterns
notebooks_exclude = [
    "scripts/ibm-quantum-learning-uploader/test/template.ipynb",
    "**/.ipynb_checkpoints/**",
    # The following notebooks are broken and need fixing
    "tutorials/submitting-transpiled-circuits/submitting-transpiled-circuits.ipynb",
]

# The following notebooks submit jobs that can be mocked with a simulator
notebooks_that_submit_jobs = [
    "tutorials/build-repetition-codes/build-repetition-codes.ipynb",
    "tutorials/chsh-inequality/chsh-inequality.ipynb",
    "tutorials/grovers-algorithm/grovers.ipynb",
    "tutorials/quantum-approximate-optimization-algorithm/qaoa.ipynb",
    "tutorials/repeat-until-success/repeat-until-success.ipynb",
    "tutorials/variational-quantum-eigensolver/vqe.ipynb",
]

# The following notebooks submit jobs that are too big to mock with a simulator
notebooks_no_mock = [
    "docs/start/hello-world.ipynb",
]
