# This code is a Qiskit project.
#
# (C) Copyright IBM 2024.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Deploy tutorials
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Where to upload the tutorials. Either "Learning platform (staging)" or "Learning platform (production)".
        required: true
jobs:
  deploy:
    name: Deploy tutorials to learning platform
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install tool
        run: pip install ./scripts/ibm-quantum-learning-uploader
      - name: Upload tutorials
        run: |
          cd tutorials
          sync-lessons
        env:
          LEARNING_API_TOKEN: ${{ secrets.LEARNING_API_TOKEN }}
          LEARNING_API_ENVIRONMENT: ${{ vars.LEARNING_API_ENVIRONMENT }}
